# Pandas

In [3]:
import pandas as pd
dicts = {"Name" : ["Sailaja Sree","Ritvika","Abhijith"],
         "Age" : [23,15,12],
         "City" : ["Adoni","Hyderabad","Hebutam"]
        }
dicts

{'Name': ['Sailaja Sree', 'Ritvika', 'Abhijith'],
 'Age': [23, 15, 12],
 'City': ['Adoni', 'Hyderabad', 'Hebutam']}

In [4]:
df=pd.DataFrame(dicts)
df

           Name  Age       City
0  Sailaja Sree   23      Adoni
1       Ritvika   15  Hyderabad
2      Abhijith   12    Hebutam

In [5]:
df=pd.read_csv("C:\\Users\\yuvra\\Downloads\\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [6]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [7]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:
df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2,0

In [9]:
df.shape

(303, 14)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [11]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [12]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [13]:
df.isnull()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [16]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [18]:
df['target']

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [19]:
df[["age","sex","cp"]]

     age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [20]:
int_columns=df.select_dtypes(include=["int","float"]).columns
int_columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [21]:
len(int_columns)

14

In [22]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [23]:
df.drop("exang", axis=1)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0.0,1,1,2,0

In [24]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool

In [25]:
df.duplicated().sum()

1

In [26]:
df.drop_duplicates()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [27]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [28]:
df["target"].value_counts(dropna=True)

target
1    165
0    138
Name: count, dtype: int64

In [29]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [30]:
df.drop

<bound method DataFrame.drop of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [31]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [32]:
df.rename(columns = {"target" : "Result", "sex" : "Gender"}, inplace=True)
df.columns

Index(['age', 'Gender', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'Result'],
      dtype='object')

In [33]:
df=pd.read_csv("C:\\Users\\yuvra\\Downloads\\dataset.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [34]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [35]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [36]:
df.rename(columns = {"target" : "Result", "sex" : "Gender"}, inplace=True)
df.columns

Index(['age', 'Gender', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'Result'],
      dtype='object')

In [37]:
df.rename(index={0:"First",1:"Second"})

,age,Gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Result
First,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
Second,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [38]:
# List Comprehension : Using this method we can capitalize the starting letters of columns
df.columns=[Col.title() for Col in df.columns]
df.columns

Index(['Age', 'Gender', 'Cp', 'Trestbps', 'Chol', 'Fbs', 'Restecg', 'Thalach',
       'Exang', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Result'],
      dtype='object')

In [39]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [40]:
df.add_prefix("Column_")

,Column_Age,Column_Gender,Column_Cp,Column_Trestbps,Column_Chol,Column_Fbs,Column_Restecg,Column_Thalach,Column_Exang,Column_Oldpeak,Column_Slope,Column_Ca,Column_Thal,Column_Result
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [41]:
df["Oldpeak"] = df["Oldpeak"].astype(int)

In [42]:
df["Oldpeak"]

0      2
1      3
2      1
3      0
4      0
      ..
298    0
299    1
300    3
301    1
302    0
Name: Oldpeak, Length: 303, dtype: int32

In [43]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0

In [44]:
select_int = df.select_dtypes(include=["int"]).columns

for col in select_int:
    df[col] = df[col].astype(float)

In [45]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63.0,1.0,3.0,145.0,233.0,1.0,0.0,150.0,0.0,2.0,0.0,0.0,1.0,1.0
1,37.0,1.0,2.0,130.0,250.0,0.0,1.0,187.0,0.0,3.0,0.0,0.0,2.0,1.0
2,41.0,0.0,1.0,130.0,204.0,0.0,0.0,172.0,0.0,1.0,2.0,0.0,2.0,1.0
3,56.0,1.0,1.0,120.0,236.0,0.0,1.0,178.0,0.0,0.0,2.0,0.0,2.0,1.0
4,57.0,0.0,0.0,120.0,354.0,0.0,1.0,163.0,1.0,0.0,2.0,0.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0.0,0.0,140.0,241.0,0.0,1.0,123.0,1.0,0.0,1.0,0.0,3.0,0.0
299,45.0,1.0,3.0,110.0,264.0,0.0,1.0,132.0,0.0,1.0,1.0,0.0,3.0,0.0
300,68.0,1.0,0.0,144.0,193.0,1.0,1.0,141.0,0.0,3.0,1.0,2.0,3.0,0.0
301,57.0,1.0,0.0,130.0,131.0,0.0,1.0,115.0,1.0,1.0,1.0,1.0,3.0,0.0
302,57.0,0.0,1.0,130.0,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0,0.0

In [46]:
select_float = df.select_dtypes(include=["float"]).columns

for col in select_float:
    df[col] = df[col].astype(int)

In [47]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0

In [48]:
df = df.astype(str)

In [49]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0

In [50]:
df = df.astype(float)

In [51]:
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63.0,1.0,3.0,145.0,233.0,1.0,0.0,150.0,0.0,2.0,0.0,0.0,1.0,1.0
1,37.0,1.0,2.0,130.0,250.0,0.0,1.0,187.0,0.0,3.0,0.0,0.0,2.0,1.0
2,41.0,0.0,1.0,130.0,204.0,0.0,0.0,172.0,0.0,1.0,2.0,0.0,2.0,1.0
3,56.0,1.0,1.0,120.0,236.0,0.0,1.0,178.0,0.0,0.0,2.0,0.0,2.0,1.0
4,57.0,0.0,0.0,120.0,354.0,0.0,1.0,163.0,1.0,0.0,2.0,0.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0.0,0.0,140.0,241.0,0.0,1.0,123.0,1.0,0.0,1.0,0.0,3.0,0.0
299,45.0,1.0,3.0,110.0,264.0,0.0,1.0,132.0,0.0,1.0,1.0,0.0,3.0,0.0
300,68.0,1.0,0.0,144.0,193.0,1.0,1.0,141.0,0.0,3.0,1.0,2.0,3.0,0.0
301,57.0,1.0,0.0,130.0,131.0,0.0,1.0,115.0,1.0,1.0,1.0,1.0,3.0,0.0
302,57.0,0.0,1.0,130.0,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0,0.0

In [52]:
df = df.astype(int)
df

,Age,Gender,Cp,Trestbps,Chol,Fbs,Restecg,Thalach,Exang,Oldpeak,Slope,Ca,Thal,Result
0,63,1,3,145,233,1,0,150,0,2,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0,1,1,2,0

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.dtypes

In [ ]:
df.isnull().sum()

In [ ]:
df.isna().sum()

In [ ]:
df["City"]

In [ ]:
df[["Name"]]

In [ ]:
df["Age"].value_counts(dropna=True)

In [ ]:
df["Age"].fillna('unknown',inplace=True)
df

In [ ]:
age_mean = int(df["Age"].mean())
age_mean

In [ ]:
df.mean()

In [ ]:
Gender_median = int(df["Gender"].median())
Gender_median

In [ ]:
df.median()

In [ ]:
df=df.astype(float)
df

In [ ]:
df=df.astype(int)
df

In [ ]:
df["Age"] = df["Age"].astype(str)

In [ ]:
df

In [ ]:
df[["Gender"]]

In [ ]:
df[["Trestbps"]]

In [ ]:
select_cols = ["Age","Trestbps"]
for col in select_cols:
    df[col] = df[col].astype(str)

In [ ]:
select_cols

In [64]:
import pandas as pd

data = {
    "CustomerId" : [101,102,103,104,105,106,107,108,109,110],
    "Name" : ["Sailu","Mahi","Yuvaraj","Prakash","Murali","Hari","Suresh","Rithu","Abhi","Padma"],
    "Age" : [25,30,35,28,40,32,27,45,38,29],
    "Gender" : ["Female","Male","Male","Male","Male","Male","Male","Female","Male","Female"],
    "Balance" : [50000,60000,45000,70000,30000,80000,55000,90000,65000,40000],
    "Salary" : [30000,45000,35000,50000,25000,60000,40000,75000,55000,32000],
    "Exited" : [0,1,0,0,1,0,1,0,0,1]
}

df = pd.DataFrame(data)

df

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [66]:
df=pd.read_csv("C:\\Users\\yuvra\\Downloads\\Bank_customer_churn.csv.crdownload")
df

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yuvra\\Downloads\\Bank_customer_churn.csv.crdownload'

In [67]:
df.head()

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1

In [68]:
df.tail()

   CustomerId    Name  Age  Gender  Balance  Salary  Exited
5         106    Hari   32    Male    80000   60000       0
6         107  Suresh   27    Male    55000   40000       1
7         108   Rithu   45  Female    90000   75000       0
8         109    Abhi   38    Male    65000   55000       0
9         110   Padma   29  Female    40000   32000       1

In [69]:
df.isnull().sum()

CustomerId    0
Name          0
Age           0
Gender        0
Balance       0
Salary        0
Exited        0
dtype: int64

In [70]:
df.isna().sum()

CustomerId    0
Name          0
Age           0
Gender        0
Balance       0
Salary        0
Exited        0
dtype: int64

In [71]:
df.describe()

       CustomerId        Age       Balance        Salary     Exited
count    10.00000  10.000000     10.000000     10.000000  10.000000
mean    105.50000  32.900000  58500.000000  44700.000000   0.400000
std       3.02765   6.436873  18416.478129  15520.953579   0.516398
min     101.00000  25.000000  30000.000000  25000.000000   0.000000
25%     103.25000  28.250000  46250.000000  32750.000000   0.000000
50%     105.50000  31.000000  57500.000000  42500.000000   0.000000
75%     107.75000  37.250000  68750.000000  53750.000000   1.000000
max     110.00000  45.000000  90000.000000  75000.000000   1.000000

In [73]:
df["Balance"].value_counts()

Balance
50000    1
60000    1
45000    1
70000    1
30000    1
80000    1
55000    1
90000    1
65000    1
40000    1
Name: count, dtype: int64

In [ ]:
df.info()

In [75]:
df["Age"]=df["Age"].astype(int)

In [76]:
df["Age"]

0    25
1    30
2    35
3    28
4    40
5    32
6    27
7    45
8    38
9    29
Name: Age, dtype: int32

In [77]:
df=df.astype(int)
df

ValueError: invalid literal for int() with base 10: 'Sailu'

In [79]:
df

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [80]:
df.columns

Index(['CustomerId', 'Name', 'Age', 'Gender', 'Balance', 'Salary', 'Exited'], dtype='object')

In [81]:
df.duplicated().sum()

0

In [82]:
# method 17 : drop_duplicates()

df.drop_duplicates(inplace = True)

In [83]:
df.duplicated().sum()

0

In [84]:
# method 23 : ffill
df['Age'].fillna(method = "ffill",inplace = True)

C:\Users\yuvra\AppData\Local\Temp\ipykernel_10892\2206171685.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(method = "ffill",inplace = True)
C:\Users\yuvra\AppData\Local\Temp\ipykernel_10892\2206171685.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method = "ffill",inplace = True)

In [85]:
# method 24: bfill:
df['Age'].fillna(method = "bfill",inplace = True)
df

C:\Users\yuvra\AppData\Local\Temp\ipykernel_10892\1648106835.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(method = "bfill",inplace = True)
C:\Users\yuvra\AppData\Local\Temp\ipykernel_10892\1648106835.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Age'].fillna(method = "bfill",inplace = True)

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [86]:
# method 27 : replace() : replace value with another value

df.replace({'Gender': {'Male': '1', 'Female': '0'}},inplace = True)

In [87]:
df

   CustomerId     Name  Age Gender  Balance  Salary  Exited
0         101    Sailu   25      0    50000   30000       0
1         102     Mahi   30      1    60000   45000       1
2         103  Yuvaraj   35      1    45000   35000       0
3         104  Prakash   28      1    70000   50000       0
4         105   Murali   40      1    30000   25000       1
5         106     Hari   32      1    80000   60000       0
6         107   Suresh   27      1    55000   40000       1
7         108    Rithu   45      0    90000   75000       0
8         109     Abhi   38      1    65000   55000       0
9         110    Padma   29      0    40000   32000       1

In [88]:
# method 27 : replace() : replace value with another value

df.replace({'Gender': {'1': 'Male', '0': 'Female'}},inplace = True)

In [89]:
df

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [90]:
#  SORTING()

#method 28 : sort_values() --  sort the column values

df.sort_values('Age', ascending=False)

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
7         108    Rithu   45  Female    90000   75000       0
4         105   Murali   40    Male    30000   25000       1
8         109     Abhi   38    Male    65000   55000       0
2         103  Yuvaraj   35    Male    45000   35000       0
5         106     Hari   32    Male    80000   60000       0
1         102     Mahi   30    Male    60000   45000       1
9         110    Padma   29  Female    40000   32000       1
3         104  Prakash   28    Male    70000   50000       0
6         107   Suresh   27    Male    55000   40000       1
0         101    Sailu   25  Female    50000   30000       0

In [91]:
# method  29 : sort_index() sort the index
df.sort_index(ascending=True)

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [92]:
# method  29 : sort_index() sort the index
df.sort_index(ascending=True)

   CustomerId     Name  Age  Gender  Balance  Salary  Exited
0         101    Sailu   25  Female    50000   30000       0
1         102     Mahi   30    Male    60000   45000       1
2         103  Yuvaraj   35    Male    45000   35000       0
3         104  Prakash   28    Male    70000   50000       0
4         105   Murali   40    Male    30000   25000       1
5         106     Hari   32    Male    80000   60000       0
6         107   Suresh   27    Male    55000   40000       1
7         108    Rithu   45  Female    90000   75000       0
8         109     Abhi   38    Male    65000   55000       0
9         110    Padma   29  Female    40000   32000       1

In [95]:
# GROUPING & AGGREGATION
df.groupby("CustomerId")["Age"].mean()

CustomerId
101    25.0
102    30.0
103    35.0
104    28.0
105    40.0
106    32.0
107    27.0
108    45.0
109    38.0
110    29.0
Name: Age, dtype: float64

In [96]:
df.groupby(["CustomerId","Gender"])['Age'].mean()

CustomerId  Gender
101         Female    25.0
102         Male      30.0
103         Male      35.0
104         Male      28.0
105         Male      40.0
106         Male      32.0
107         Male      27.0
108         Female    45.0
109         Male      38.0
110         Female    29.0
Name: Age, dtype: float64

In [97]:
df["Age_Level"]= ["Older" if age > 45 else "Young" for age in  df['Age']]

In [98]:
df["Age_Level"]

0    Young
1    Young
2    Young
3    Young
4    Young
5    Young
6    Young
7    Young
8    Young
9    Young
Name: Age_Level, dtype: object

In [99]:
df["Age_Level"].value_counts()

Age_Level
Young    10
Name: count, dtype: int64

In [109]:
import pandas as pd
df = pd.DataFrame({'date': [ 
    '2024-01-15',      # YYYY-MM-DD 
    '15/01/2024',      # DD/MM/YYYY 
    '01-15-2024',      # MM-DD-YYYY 
    'Jan 15 2024',     # Month name 
    '15 January 2024', # Full month name 
    '20240115'         # Compact format 
]}) 
 
# Auto detect format 
df['date'] = pd.to_datetime(df['date'],format='mixed', dayfirst=True) 
df

        date
0 2024-01-15
1 2024-01-15
2 2024-01-15
3 2024-01-15
4 2024-01-15
5 2024-01-15

In [104]:
import pandas as pd

df = pd.DataFrame({'date': [
    '2024-01-15',
    '15/01/2024',
    '01-15-2024',
    'Jan 15 2024',
    '15 January 2024',
    '20240115'
]})

df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=True)

df

        date
0 2024-01-15
1 2024-01-15
2 2024-01-15
3 2024-01-15
4 2024-01-15
5 2024-01-15